###############################################################################
# OVERVIEW
###############################################################################
# The following contains the pre-commit hooks for this repository, which are
# likely a modified version of the author's (O957) repository template.
#
# Links:
#
# Pre-commit: https://pre-commit.com/
# The author's template: https://github.com/O957/O957-Template
# Supported hooks: https://github.com/pre-commit/pre-commit-hooks
# Ruff rules: https://docs.astral.sh/ruff/rules/
###############################################################################
# CONTINUOUS INTEGRATION
###############################################################################
ci:
    # custom commit message for PR autofixes
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
    # whether to autofix pull requests. when disabled, comment / label
    # "pre-commit.ci autofix" to a pull request to manually trigger
    # auto-fixing.
    autofix_prs: true
    # branch to send autoupdate PRs to; by default, pre-commit.ci will update
    # the default branch of the repository.
    autoupdate_branch: ""
    # custom commit message for autoupdate PRs.
    autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
    # control when the autoupdate runs, possible values: 'weekly',
    # 'monthly', 'quarterly'.
    autoupdate_schedule: weekly
    # a list of hook ids to skip only in pre-commit.ci;
    skip: []
    #  whether to recursively check out submodules
    submodules: false
###############################################################################
# GENERAL
###############################################################################
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    # prevent giant files from being committed.
    -   id: check-added-large-files
        args: ["--maxkb=10000"]
    # simply check whether files parse as valid
    # python
    -   id: check-ast
    # check for files with names that would
    # conflict on a case-insensitive filesystem
    # like MacOS HFS+ or Windows FAT.
    -   id: check-case-conflict
    # checks for a common error of placing
    # code before the docstring.
    -   id: check-docstring-first
    # attempts to load all yaml files to
    # verify syntax.
    -   id: check-yaml
        # allow yaml files which use the
        # multi-document syntax
        args: ["--allow-multiple-documents"]
    # attempts to load all TOML files to
    # verify syntax.
    -   id: check-toml
    # makes sure files end in a newline and
    # only a newline.
    -   id: end-of-file-fixer
    # replaces or checks mixed line ending.
    -   id: mixed-line-ending
    # verifies that test files are named
    # correctly.
    -   id: name-tests-test
        # ensure tests match test_.*\.py
        args: ["--pytest-test-first"]
    # checks that all your JSON files are pretty.
    # "Pretty" here means that keys are sorted
    # and indented.
    -   id: pretty-format-json
        # automatically format json files;
        # when autofixing, retain the original
        # key ordering (instead of sorting
        # the keys)
        args: ["--autofix", "--no-sort-keys",  "--indent", "4"]
    # trims trailing whitespace.
    -   id: trailing-whitespace
    # checks that non-binary executables have
    # a proper shebang.
    -   id: check-executables-have-shebangs
        files: \.sh$
    # checks for the existence of private keys.
    -   id: detect-private-key
###############################################################################
# PYTHON
###############################################################################
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
    # "currently, the Ruff formatter does not sort imports.
    # In order to both sort imports and format, call
    # the Ruff linter and then the formatter:"
    -   id: ruff
        args: [
          "check",
          "--select",
          # isort
          "I",
          "--fix"
        ]
    # run ruff linter; the Ruff Linter is an extremely fast Python linter
    # designed as a drop-in replacement for Flake8 (plus dozens of plugins),
    # isort, pydocstyle, pyupgrade, autoflake, and more
    -   id: ruff
        args: [
          # ambiguous variable name: {name}
          "--ignore=E741",
          # do not assign a lambda expression, use a def
          "--ignore=E731",
          # indentation contains tabs (sorry, I like tabs)
          "--ignore=W191",
          # found useless expression. ignore since .qmd displays
          "--ignore=B018",
          # {name} is too complex ({complexity} > {max_complexity})
          # note: ignored on select repositories
          "--ignore=C901",
          # E and W: pycodestyle, standard PEP8 errors and pycodestyle warnings.
          # F: pyflakes warnings (e.g., unused variables, undefined names).,
          # B: flake8-bugbear (useful best practices).
          # SIM: flake8-simplify
          # C90: McCabe complexity (cyclomatic complexity).
          # UP: pyupgrade, Python version compatibility
          "--select=E,W,F,B,C90,UP,SIM",
          # linter checks for lines, but doesn't fix, default is 88
          "--line-length=79",
          # lint all files in the current directory, and fix any fixable errors.
          "--fix"
        ]
    # run the ruff-formatter; the Ruff formatter is an extremely fast
    # Python code formatter designed as a drop-in replacement for Black
    -   id: ruff-format
        args: [
          "--line-length=79",
        ]
###############################################################################
# XENON CODE COMPLEXITY
###############################################################################
-   repo: https://github.com/rubik/xenon
    rev: v0.9.3
    hooks:
    -   id: xenon
        args: [
            # threshold for the average complexity
            # (across all the codebase).
            "--max-absolute=B",
            # threshold for modules complexity.
            "--max-modules=B",
            # absolute threshold for block complexity.
            "--max-average=A"
        ]
###############################################################################
# UV PACKAGE AND DEPENDENCY MANAGEMENT
###############################################################################
-   repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.13
    hooks:
    -   id: uv-lock
###############################################################################
# MAKE FILES
###############################################################################
-   repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
    -   id: checkmake
###############################################################################
# SECURITY
###############################################################################
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    # must first run
    # detect-secrets scan > .secrets.baseline
    -   id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json
###############################################################################
# GITHUB ACTIONS
###############################################################################
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
    -   id: actionlint
###############################################################################
# SPELLING
###############################################################################
-   repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
    -   id: typos
        args: ["--force-exclude"]
###############################################################################
# COMMIT MESSAGES
###############################################################################
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
    -   id: commitizen
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
    -   id: gitlint
###############################################################################
